version: '3.4'

services:
  postgres:
    container_name: its-leif-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: { { postgres_user } }
      POSTGRES_DB: { { postgres_db } }
      POSTGRES_PASSWORD: { { postgres_passsword } }

volumes:
  postgres_data:
